export const GET_UNITS_REQUEST = 'GET_UNITS_REQUEST'
export const GET_UNITS_FULFILLED = 'GET_UNITS_FULFILLED'

export const GET_UNIT_TYPES_REQUEST = 'GET_UNIT_TYPES_REQUEST'
export const GET_UNIT_TYPES_FULFILLED = 'GET_UNIT_TYPES_FULFILLED'